// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy3adXLsDrg6G9VkXUDAjcIrxQ6OZjWfI',
    appId: '1:294505454240:web:ba8c296c7e2bc2c89e07c5',
    messagingSenderId: '294505454240',
    projectId: 'dice-2023',
    authDomain: 'dice-2023.firebaseapp.com',
    storageBucket: 'dice-2023.appspot.com',
    measurementId: 'G-2846RVK3JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGtGROb4PIbhchLrj3_pLX0UWX6nGwbt8',
    appId: '1:294505454240:android:270f206450b210b89e07c5',
    messagingSenderId: '294505454240',
    projectId: 'dice-2023',
    storageBucket: 'dice-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg_JPLzOLgbg5HtphQz7fbeDCAxgEOMws',
    appId: '1:294505454240:ios:7b24b5a3520601e59e07c5',
    messagingSenderId: '294505454240',
    projectId: 'dice-2023',
    storageBucket: 'dice-2023.appspot.com',
    iosClientId: '294505454240-6d5m4hehj34mr219m9du5j873bebb2qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.dice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg_JPLzOLgbg5HtphQz7fbeDCAxgEOMws',
    appId: '1:294505454240:ios:7b24b5a3520601e59e07c5',
    messagingSenderId: '294505454240',
    projectId: 'dice-2023',
    storageBucket: 'dice-2023.appspot.com',
    iosClientId: '294505454240-6d5m4hehj34mr219m9du5j873bebb2qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.dice',
  );
}
